#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 14 09:54:20 2020

@author: thalitaramires
"""
#Challenge01
#-------------------------------------------------------------

#The examples below show you how to write function accum:
#Examples:
    
#accum("abcd") -> "A-Bb-Ccc-Dddd"
#accum("RqaEzty") -> "R-Qq-Aaa-Eeee-Zzzzz-Tttttt-Yyyyyyy"
#accum("cwAt") -> "C-Ww-Aaa-Tttt"
#The parameter of accum is a string which includes only letters from a..z and A..Z.

#---------------------------------------------------------------

def accum(arg1):
    res = ' '
    for i in range(len(arg1)):
        newValue = arg1[i] * (i + 1)
        if i == len(arg1) -1 :
            res = res + newValue.capitalize()
        else:
            res = res + newValue.capitalize() + '-'
    return res

x = accum('rebel')
print('Resultado: ', x)

    
